/**
 * TypeScript code generator: turns a validated ProtoFile into a module of
 * interfaces + descriptors + typed encode/decode wrappers on top of the
 * shared runtime.
 */

import { SCALAR_TYPES } from "./parser.js";
import type { MessageDecl, ProtoFile } from "./parser.js";

export interface CodegenOptions {
  /** Original .proto file name, for the header comment. */
  sourceName: string;
  /** Module specifier the generated file uses to import the runtime. */
  runtimeImport: string;
}

const SCALAR_SET = new Set<string>(SCALAR_TYPES);

const TS_TYPE: Record<string, string> = {
  int32: "number",
  uint32: "number",
  sint32: "number",
  bool: "boolean",
  string: "string",
  bytes: "Uint8Array",
};

function emitDoc(out: string[], doc: string[], indent: string): void {
  if (doc.length === 0) return;
  out.push(`${indent}/**`);
  for (const comment of doc) {
    for (const line of comment.split("\n")) {
      out.push(`${indent} * ${line.replaceAll("*/", "*\\/")}`);
    }
  }
  out.push(`${indent} */`);
}

function emitMessage(out: string[], m: MessageDecl): void {
  emitDoc(out, m.doc, "");
  out.push(`export interface ${m.name} {`);
  for (const f of m.fields) {
    emitDoc(out, f.doc, "  ");
    const tsType = TS_TYPE[f.typeName] ?? f.typeName;
    const opt = f.label === "optional" ? "?" : "";
    const arr = f.label === "repeated" ? "[]" : "";
    out.push(`  ${f.name}${opt}: ${tsType}${arr};`);
  }
  out.push(`}`);
  out.push(``);
  out.push(`export const ${m.name}$desc: rt.MessageDesc = {`);
  out.push(`  name: ${JSON.stringify(m.name)},`);
  out.push(`  fields: [`);
  for (const f of m.fields) {
    const isScalar = SCALAR_SET.has(f.typeName);
    const parts = [
      `no: ${f.no}`,
      `name: ${JSON.stringify(f.name)}`,
      `label: ${JSON.stringify(f.label)}`,
      `type: ${JSON.stringify(isScalar ? f.typeName : "message")}`,
    ];
    if (f.packed) parts.push(`packed: true`);
    if (!isScalar) parts.push(`msg: () => ${f.typeName}$desc`);
    out.push(`    { ${parts.join(", ")} },`);
  }
  out.push(`  ],`);
  out.push(`};`);
  out.push(``);
  out.push(`export function encode${m.name}(msg: ${m.name}): Uint8Array {`);
  out.push(`  return rt.encodeMessage(${m.name}$desc, msg);`);
  out.push(`}`);
  out.push(``);
  out.push(`export function decode${m.name}(buf: Uint8Array): ${m.name} {`);
  out.push(`  return rt.decodeMessage(${m.name}$desc, buf);`);
  out.push(`}`);
  out.push(``);
}

export function generateTs(file: ProtoFile, opts: CodegenOptions): string {
  const out: string[] = [];
  out.push(
    `// Code generated by proto2ts from ${opts.sourceName}. DO NOT EDIT.`,
  );
  out.push(
    `// syntax: proto2${file.packageName !== undefined ? `   package: ${file.packageName}` : ""}`,
  );
  out.push(``);
  out.push(`import * as rt from ${JSON.stringify(opts.runtimeImport)};`);
  out.push(``);
  for (const m of file.messages) emitMessage(out, m);
  return out.join("\n");
}
