/**
 * Compiler tests: lexing, parsing, validation and code generation from
 * actual .proto text (never from pre-digested field JSON).
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import {
  compileProto,
  parseProto,
  CompileError,
} from "../src/compiler/index.js";

const OPTS = {
  sourceName: "test.proto",
  runtimeImport: "../src/runtime/runtime.js",
};

function compileErr(src: string): string {
  try {
    parseProto(src);
  } catch (e) {
    assert.ok(
      e instanceof CompileError,
      `expected CompileError, got ${String(e)}`,
    );
    return (e as Error).message;
  }
  throw new Error("expected compilation to fail, but it succeeded");
}

// ----- happy paths -----------------------------------------------------------

test("parses a full file: syntax, package, comments, all field kinds", () => {
  const file = parseProto(`
// leading file comment
syntax = "proto2";
package acme.demo;

// A doc comment for Person.
message Person {
  required string name = 1;
  optional int32 age = 2;   // trailing comment for age
  repeated sint32 scores = 3 [packed = true];
  optional bytes raw = 4;
  optional bool ok = 5;
  optional uint32 count = 6;
  /* block comment */
  optional Address addr = 7;  // forward reference, declared below
}

message Address {
  required string city = 1;
}
`);
  assert.equal(file.syntax, "proto2");
  assert.equal(file.packageName, "acme.demo");
  assert.equal(file.messages.length, 2);
  const [person, address] = file.messages;
  assert.equal(person!.name, "Person");
  assert.deepEqual(person!.doc, ["A doc comment for Person."]);
  assert.equal(person!.fields.length, 7);
  assert.deepEqual(person!.fields[1]!.doc, ["trailing comment for age"]);
  assert.equal(person!.fields[2]!.packed, true);
  assert.equal(person!.fields[6]!.typeName, "Address");
  assert.equal(address!.name, "Address");
});

test("forward and self type references resolve", () => {
  const file = parseProto(`
message A { optional B b = 1; }
message B { optional A a = 1; optional B self = 2; }
`);
  assert.equal(file.messages.length, 2);
});

test("syntax line is optional (proto2 is the default)", () => {
  const file = parseProto(`message M { required int32 x = 1; }`);
  assert.equal(file.syntax, "proto2");
});

test("codegen emits interfaces, descriptors and wrappers", () => {
  const ts = compileProto(
    `
// Doc for M.
message M {
  required string s = 1;   // doc for s
  repeated int32 n = 2 [packed = true];
  optional N sub = 3;
}
message N { optional bytes b = 1; }
`,
    OPTS,
  );
  assert.match(ts, /Code generated by proto2ts from test\.proto/);
  assert.match(ts, /import \* as rt from "\.\.\/src\/runtime\/runtime\.js";/);
  assert.match(ts, /export interface M \{/);
  assert.match(ts, /\* doc for s/);
  assert.match(ts, /s: string;/);
  assert.match(ts, /n: number\[\];/);
  assert.match(ts, /sub\?: N;/);
  assert.match(
    ts,
    /\{ no: 2, name: "n", label: "repeated", type: "int32", packed: true \}/,
  );
  assert.match(ts, /msg: \(\) => N\$desc/);
  assert.match(ts, /export function encodeM\(msg: M\): Uint8Array/);
  assert.match(ts, /export function decodeN\(buf: Uint8Array\): N/);
});

// ----- validation errors ------------------------------------------------------

test("duplicate message names are reported", () => {
  const msg = compileErr(`
message A { optional int32 x = 1; }
message A { optional int32 y = 1; }
`);
  assert.match(msg, /duplicate message name 'A'/);
  assert.match(msg, /first declared at 2:1/);
});

test("message names may not collide with scalar types", () => {
  assert.match(
    compileErr(`message string { optional int32 x = 1; }`),
    /conflicts with a built-in scalar/,
  );
});

test("duplicate field names are reported", () => {
  assert.match(
    compileErr(`message A { optional int32 x = 1; optional string x = 2; }`),
    /duplicate field name 'x' in message 'A'/,
  );
});

test("duplicate field numbers are reported", () => {
  assert.match(
    compileErr(`message A { optional int32 x = 1; optional string y = 1; }`),
    /duplicate field number 1 in message 'A' \(already used by field 'x'\)/,
  );
});

test("illegal field numbers are reported", () => {
  assert.match(
    compileErr(`message A { optional int32 x = 0; }`),
    /illegal field number 0/,
  );
  assert.match(
    compileErr(`message A { optional int32 x = 536870912; }`),
    /illegal field number 536870912/,
  );
  assert.match(
    compileErr(`message A { optional int32 x = 19000; }`),
    /reserved/,
  );
  assert.match(
    compileErr(`message A { optional int32 x = 19999; }`),
    /reserved/,
  );
  // boundaries that must be accepted
  parseProto(
    `message A { optional int32 a = 1; optional int32 b = 536870911; optional int32 c = 18999; optional int32 d = 20000; }`,
  );
});

test("unknown field types are reported, even across messages", () => {
  assert.match(
    compileErr(`message A { optional Missing m = 1; }`),
    /unknown type 'Missing' on field 'A\.m'/,
  );
});

test("packed is rejected on non-repeated, non-numeric or message fields", () => {
  assert.match(
    compileErr(`message A { optional int32 x = 1 [packed = true]; }`),
    /'packed'.*only allowed for repeated numeric scalar/,
  );
  assert.match(
    compileErr(`message A { repeated string x = 1 [packed = true]; }`),
    /'packed'/,
  );
  assert.match(
    compileErr(`message A { repeated bytes x = 1 [packed = true]; }`),
    /'packed'/,
  );
  assert.match(
    compileErr(
      `message B { optional int32 y = 1; } message A { repeated B x = 1 [packed = true]; }`,
    ),
    /'packed'/,
  );
  // packed = false is equally out of place on an optional field
  assert.match(
    compileErr(`message A { optional int32 x = 1 [packed = false]; }`),
    /'packed'/,
  );
  // legal uses compile fine
  parseProto(
    `message A { repeated int32 a = 1 [packed = true]; repeated bool b = 2 [packed = false]; repeated sint32 c = 3 [packed = true]; repeated uint32 d = 4 [packed = true]; }`,
  );
});

test("more than 6 top-level messages are rejected", () => {
  const src = Array.from(
    { length: 7 },
    (_, i) => `message M${i} { optional int32 x = 1; }`,
  ).join("\n");
  assert.match(compileErr(src), /at most 6 top-level messages/);
  parseProto(
    Array.from(
      { length: 6 },
      (_, i) => `message M${i} { optional int32 x = 1; }`,
    ).join("\n"),
  );
});

test("an empty file is rejected", () => {
  assert.match(compileErr(`syntax = "proto2";`), /no messages/);
});

test("unsupported syntax versions are rejected", () => {
  assert.match(
    compileErr(`syntax = "proto3"; message A { optional int32 x = 1; }`),
    /only "proto2" is supported/,
  );
});

test("unsupported constructs fail with clear errors", () => {
  assert.match(
    compileErr(`import "other.proto"; message A { optional int32 x = 1; }`),
    /'import' is not supported/,
  );
  assert.match(
    compileErr(`message A { oneof x { int32 a = 1; } }`),
    /'oneof' is not supported/,
  );
  assert.match(
    compileErr(`message A { optional group G = 1 { } }`),
    /'group' is not supported/,
  );
  assert.match(
    compileErr(`message A { map<string, int32> m = 1; }`),
    /'map' is not supported/,
  );
  assert.match(
    compileErr(`message A { reserved 2; optional int32 x = 1; }`),
    /'reserved' is not supported/,
  );
  assert.match(
    compileErr(`message A { message B { } optional int32 x = 1; }`),
    /'message' is not supported inside a message/,
  );
  assert.match(
    compileErr(`enum E { A = 0; } message A { optional int32 x = 1; }`),
    /'enum' is not supported/,
  );
  assert.match(
    compileErr(`message A { optional int32 x = 1 [default = 5]; }`),
    /unsupported field option 'default'/,
  );
  assert.match(
    compileErr(`message A { optional int32 x = 1 [packed = yes]; }`),
    /packed must be 'true' or 'false'/,
  );
});

test("syntax errors carry line and column", () => {
  const msg = compileErr(`message A {
  optional int32 x = 1
  optional int32 y = 2;
}`);
  assert.match(msg, /^3:3: expected ';'/m);
});

test("unterminated block comment fails", () => {
  assert.match(
    compileErr(`message A { optional int32 x = 1; } /* oops`),
    /unterminated block comment/,
  );
});

test("multiple validation problems are reported together", () => {
  const msg = compileErr(`message A {
  optional int32 x = 1;
  optional string x = 1;
  optional Missing y = 19000;
}`);
  assert.match(msg, /duplicate field name 'x'/);
  assert.match(msg, /duplicate field number 1/);
  assert.match(msg, /unknown type 'Missing'/);
  assert.match(msg, /reserved/);
  assert.equal(msg.trim().split("\n").length, 4);
});

test("stray semicolons and empty messages are tolerated", () => {
  const file = parseProto(`; message A { ; optional int32 x = 1; ; } ;`);
  assert.equal(file.messages.length, 1);
  assert.equal(file.messages[0]!.fields.length, 1);
});
