/**
 * Integration test: exercises the module generated by our own compiler
 * (demo/addressbook.pb.ts) through its typed API.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import * as rt from "../src/runtime/runtime.js";
import {
  decodeAddressBook,
  decodeChain,
  decodePerson,
  encodeAddressBook,
  encodeChain,
  encodePerson,
} from "../demo/addressbook.pb.js";
import type { AddressBook, Chain, Person } from "../demo/addressbook.pb.js";

test("generated module round-trips a full AddressBook", () => {
  const book: AddressBook = {
    people: [
      {
        name: "Alice",
        id: -7,
        email: "alice@example.com",
        address: { street: "1 Main St", city: "Springfield" },
        deltas: [-1, 0, 1],
        lucky_numbers: [7, 13],
        active: false,
        avatar: new Uint8Array([0, 1, 2, 255]),
        score: 4000000000,
      },
      { name: "Bob", id: 2, deltas: [], lucky_numbers: [] },
    ],
    owner: { name: "Carol", id: 3, deltas: [5], lucky_numbers: [] },
  };
  const back = decodeAddressBook(encodeAddressBook(book));
  assert.equal(back.people.length, 2);
  assert.equal(back.people[0]!.id, -7);
  assert.equal(back.people[0]!.active, false); // explicit default preserved
  assert.deepEqual([...back.people[0]!.avatar!], [0, 1, 2, 255]);
  assert.equal(back.people[0]!.score, 4000000000);
  assert.equal(back.people[1]!.email, undefined); // absent stays absent
  assert.equal(back.owner!.name, "Carol");
  assert.deepEqual(back.people[0]!.address, {
    street: "1 Main St",
    city: "Springfield",
  });
});

test("generated decode handles mixed packed/unpacked wire data", () => {
  const w = new rt.Writer();
  const name = new TextEncoder().encode("P");
  w.tag(1, 2);
  w.varint(BigInt(name.length));
  w.bytes(name);
  w.tag(2, 0);
  w.varint(1n);
  // deltas (packed=true by declaration) sent as: one unpacked, one packed block
  w.tag(5, 0);
  w.varint(BigInt(rt.zigzagEncode32(-5)));
  const p = new rt.Writer();
  p.varint(BigInt(rt.zigzagEncode32(6)));
  p.varint(BigInt(rt.zigzagEncode32(-7)));
  const pb = p.finish();
  w.tag(5, 2);
  w.varint(BigInt(pb.length));
  w.bytes(pb);
  const msg = decodePerson(w.finish());
  assert.deepEqual(msg.deltas, [-5, 6, -7]);
});

test("generated decode merges duplicated nested messages before checking required", () => {
  const w = new rt.Writer();
  const name = new TextEncoder().encode("P");
  w.tag(1, 2);
  w.varint(BigInt(name.length));
  w.bytes(name);
  w.tag(2, 0);
  w.varint(1n);
  const put = (fieldNo: number, s: string) => {
    const inner = new rt.Writer();
    const b = new TextEncoder().encode(s);
    inner.tag(fieldNo, 2);
    inner.varint(BigInt(b.length));
    inner.bytes(b);
    return inner.finish();
  };
  const c1 = put(1, "street-only"); // Address.street
  const c2 = put(2, "city-only"); // Address.city
  for (const c of [c1, c2]) {
    w.tag(4, 2);
    w.varint(BigInt(c.length));
    w.bytes(c);
  }
  const msg = decodePerson(w.finish());
  assert.deepEqual(msg.address, { street: "street-only", city: "city-only" });
});

test("generated decode keeps unknown fields through modify + re-encode", () => {
  const base = encodePerson({
    name: "X",
    id: 1,
    deltas: [],
    lucky_numbers: [],
  });
  const extra = new rt.Writer();
  extra.tag(30, 0);
  extra.varint(150n);
  const buf = new Uint8Array([...base, ...extra.finish()]);
  const msg: Person = decodePerson(buf);
  msg.score = 42;
  const msg2 = decodePerson(encodePerson(msg));
  assert.equal(msg2.score, 42);
  assert.deepEqual(
    rt.getUnknownFields(msg2).map((u) => u.no),
    [30],
  );
});

test("generated Chain enforces the depth limit on both sides", () => {
  const make = (depth: number): Chain => {
    let c: Chain = { value: depth };
    for (let i = depth - 1; i >= 1; i--) c = { value: i, next: c };
    return c;
  };
  assert.doesNotThrow(() => decodeChain(encodeChain(make(8))));
  assert.throws(() => encodeChain(make(9)), rt.EncodeError);
});

test("generated encode rejects missing required fields", () => {
  assert.throws(
    // @ts-expect-error deliberately bypass the type system
    () => encodePerson({ id: 1, deltas: [], lucky_numbers: [] }),
    /Person\.name: required field is missing/,
  );
});
