// Code generated by proto2ts from addressbook.proto. DO NOT EDIT.
// syntax: proto2   package: demo

import * as rt from "../src/runtime/runtime.js";

/**
 * A postal address.
 */
export interface Address {
  street: string;
  city: string;
  zip?: string;
}

export const Address$desc: rt.MessageDesc = {
  name: "Address",
  fields: [
    { no: 1, name: "street", label: "required", type: "string" },
    { no: 2, name: "city", label: "required", type: "string" },
    { no: 3, name: "zip", label: "optional", type: "string" },
  ],
};

export function encodeAddress(msg: Address): Uint8Array {
  return rt.encodeMessage(Address$desc, msg);
}

export function decodeAddress(buf: Uint8Array): Address {
  return rt.decodeMessage(Address$desc, buf);
}

/**
 * A person in the address book.
 */
export interface Person {
  /**
   * full name
   */
  name: string;
  /**
   * may be negative, to exercise 10-byte varints
   */
  id: number;
  email?: string;
  address?: Address;
  /**
   * zigzag, packed on the wire
   */
  deltas: number[];
  /**
   * unpacked on the wire
   */
  lucky_numbers: number[];
  /**
   * presence demo: explicit false
   */
  active?: boolean;
  avatar?: Uint8Array;
  score?: number;
}

export const Person$desc: rt.MessageDesc = {
  name: "Person",
  fields: [
    { no: 1, name: "name", label: "required", type: "string" },
    { no: 2, name: "id", label: "required", type: "int32" },
    { no: 3, name: "email", label: "optional", type: "string" },
    {
      no: 4,
      name: "address",
      label: "optional",
      type: "message",
      msg: () => Address$desc,
    },
    { no: 5, name: "deltas", label: "repeated", type: "sint32", packed: true },
    { no: 6, name: "lucky_numbers", label: "repeated", type: "int32" },
    { no: 7, name: "active", label: "optional", type: "bool" },
    { no: 8, name: "avatar", label: "optional", type: "bytes" },
    { no: 9, name: "score", label: "optional", type: "uint32" },
  ],
};

export function encodePerson(msg: Person): Uint8Array {
  return rt.encodeMessage(Person$desc, msg);
}

export function decodePerson(buf: Uint8Array): Person {
  return rt.decodeMessage(Person$desc, buf);
}

/**
 * The whole address book.
 */
export interface AddressBook {
  people: Person[];
  owner?: Person;
}

export const AddressBook$desc: rt.MessageDesc = {
  name: "AddressBook",
  fields: [
    {
      no: 1,
      name: "people",
      label: "repeated",
      type: "message",
      msg: () => Person$desc,
    },
    {
      no: 2,
      name: "owner",
      label: "optional",
      type: "message",
      msg: () => Person$desc,
    },
  ],
};

export function encodeAddressBook(msg: AddressBook): Uint8Array {
  return rt.encodeMessage(AddressBook$desc, msg);
}

export function decodeAddressBook(buf: Uint8Array): AddressBook {
  return rt.decodeMessage(AddressBook$desc, buf);
}

/**
 * A linked list node; recursion exercises the depth limit.
 */
export interface Chain {
  value: number;
  next?: Chain;
}

export const Chain$desc: rt.MessageDesc = {
  name: "Chain",
  fields: [
    { no: 1, name: "value", label: "required", type: "int32" },
    {
      no: 2,
      name: "next",
      label: "optional",
      type: "message",
      msg: () => Chain$desc,
    },
  ],
};

export function encodeChain(msg: Chain): Uint8Array {
  return rt.encodeMessage(Chain$desc, msg);
}

export function decodeChain(buf: Uint8Array): Chain {
  return rt.decodeMessage(Chain$desc, buf);
}
